In [39]:
#-*- coding: utf-8 -*-
from __future__ import print_function
import pandas as pd
# from apriori import *  # 导入自行编写的apriori函数
import time  # 导入时间库用来计算用时'
import numpy as np
inputfile = 'MCM_NFLIS_Data.xlsx'  # 输入事务集文件
data = pd.read_excel(inputfile, dtype=object,sheet_name='Data')
# start = time.clock()  # 计时开始
# print(u'\n转换原始数据至0-1矩阵...')
# ct = lambda x: pd.Series(1, index=x)  # 转换0-1矩阵的过渡函数
# b = map(ct, data.as_matrix())  # 用map方式执行
# data = pd.DataFrame(b).fillna(0)  # 实现矩阵转换，空值用0填充
# end = time.clock()  # 计时结束
# print(u'\n转换完毕，用时：%0.2f秒' % (end - start))
# del b  # 删除中间变量b，节省内存

# support = 0.06  # 最小支持度
# confidence = 0.75  # 最小置信度
# ms = '---'  # 连接符，默认'--'，用来区分不同元素，如A--B。需要保证原始表格中不含有该字符

# start = time.clock()  # 计时开始
# print(u'\n开始搜索关联规则...')
# find_rule(data, support, confidence, ms)
# end = time.clock()  # 计时结束
# print(u'\n搜索完成，用时：%0.2f秒' % (end - start))
# data
data.sort_index(by='SubstanceName')
# for i in range(24061):
#     if(data[i]):
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import  train_test_split
import matplotlib.pyplot as plt
# data.index

print(data.columns)
data=data.sort_values(by='SubstanceName')
data.describe
drug=[]

for i in range(24062):
    drug.append(data.at[i,'SubstanceName'])
drug=set(drug)
dict_drug=list(drug)
dict_drug.sort()
# for i in range(len(drug)):
#     dict_drug[i]=drug.
i=[]
for _ in range(69):
    i.append(_)
print(i)
dict_drug=zip(dict_drug,i)
nvDict = dict( (name,value) for name,value in dict_drug)
print(nvDict)

Index(['YYYY', 'State', 'COUNTY', 'FIPS_State', 'FIPS_County', 'FIPS_Combined',
       'SubstanceName', 'DrugReports', 'TotalDrugReportsCounty',
       'TotalDrugReportsState'],
      dtype='object')
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]
{'3,4-Methylenedioxy U-47700': 0, '3-Fluorofentanyl': 1, '3-Methylfentanyl': 2, '4-Fluoroisobutyryl fentanyl': 3, '4-Methylfentanyl': 4, 'ANPP': 5, 'Acetyl fentanyl': 6, 'Acetylcodeine': 7, 'Acetyldihydrocodeine': 8, 'Acryl fentanyl': 9, 'Alphaprodine': 10, 'Benzylfentanyl': 11, 'Buprenorphine': 12, 'Butorphanol': 13, 'Butyryl fentanyl': 14, 'Carfentanil': 15, 'Codeine': 16, 'Crotonyl fentanyl': 17, 'Cyclopentyl fentanyl': 18, 'Cyclopropyl fentanyl': 19, 'Cyclopropyl/Crotonyl Fentanyl': 20, 'Desmethylprodine ': 21, 'Dextropropo

/Users/Macbook/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:28: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)


In [40]:
data['dict_drug']=data['SubstanceName']
data['dict_drug']=data['dict_drug'].map(nvDict)
data['FIPS_State']=data['FIPS_State'].apply(lambda x:int(x))
data['FIPS_County']=data['FIPS_County'].apply(lambda x:int(x))
data['FIPS_Combined']=data['FIPS_Combined'].apply(lambda x:int(x))

In [41]:
data=data.sort_values(by='FIPS_Combined')
data


YYYY State   COUNTY  FIPS_State  FIPS_County  FIPS_Combined  \
12164  2014    KY    ADAIR          21            1          21001   
2822   2011    KY    ADAIR          21            1          21001   
2577   2011    KY    ADAIR          21            1          21001   
5096   2012    KY    ADAIR          21            1          21001   
2821   2011    KY    ADAIR          21            1          21001   
16754  2016    KY    ADAIR          21            1          21001   
12163  2014    KY    ADAIR          21            1          21001   
401    2010    KY    ADAIR          21            1          21001   
2732   2011    KY    ADAIR          21            1          21001   
2731   2011    KY    ADAIR          21            1          21001   
13571  2015    KY    ADAIR          21            1          21001   
4910   2012    KY    ADAIR          21            1          21001   
16831  2016    KY    ADAIR          21            1          21001   
4909   2012    KY    ADAIR          21            1          21001   
8086   2013    KY    ADAIR          21            1          21001   
5320   2012    KY    ADAIR          21            1          21001   
13835  2015    KY    ADAIR          21            1          21001   
5321   2012    KY    ADAIR          21            1          21001   
4908   2012    KY    ADAIR          21            1          21001   
13645  2015    KY    ADAIR          21            1          21001   
7982   2013    KY    ADAIR          21            1          21001   
20167  2017    KY    ADAIR          21            1          21001   
16580  2016    KY    ADAIR          21            1          21001   
14087  2015    KY    ADAIR          21            1          21001   
20301  2017    KY    ADAIR          21            1          21001   
11373  2014    KY    ADAIR          21            1          21001   
5319   2012    KY    ADAIR          21            1          21001   
17409  2016    KY    ADAIR          21            1          21001   
5322   2012    KY    ADAIR          21            1          21001   
20501  2017    KY    ADAIR          21            1          21001   
...     ...   ...      ...         ...          ...            ...   
24050  2017    WV     WOOD          54          107          54107   
8080   2012    WV     WOOD          54          107          54107   
20157  2016    WV     WOOD          54          107          54107   
2726   2010    WV     WOOD          54          107          54107   
2569   2010    WV     WOOD          54          107          54107   
23245  2017    WV     WOOD          54          107          54107   
11082  2013    WV     WOOD          54          107          54107   
17020  2015    WV     WOOD          54          107          54107   
7873   2012    WV     WOOD          54          107          54107   
23246  2017    WV     WOOD          54          107          54107   
16820  2015    WV     WOOD          54          107          54107   
16482  2015    WV     WOOD          54          107          54107   
23244  2017    WV     WOOD          54          107          54107   
10653  2013    WV     WOOD          54          107          54107   
20017  2016    WV     WOOD          54          107          54107   
23941  2017    WV     WOOD          54          107          54107   
13636  2014    WV     WOOD          54          107          54107   
6051   2011    WV  WYOMING          54          109          54109   
4976   2011    WV  WYOMING          54          109          54109   
2573   2010    WV  WYOMING          54          109          54109   
11257  2013    WV  WYOMING          54          109          54109   
14391  2014    WV  WYOMING          54          109          54109   
10926  2013    WV  WYOMING          54          109          54109   
4903   2011    WV  WYOMING          54          109          54109   
13756  2014    WV  WYOMING          54          109          54109   
23842  2017    WV

In [104]:
def create_data(data):
#     iris = load_iris()
#     df = pd.DataFrame(iris.data, columns=iris.feature_names)
#     df=data
#     df.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
#     print(data)
    data = np.array(data.iloc[:, [0, 3,4,10, 7,8,9]])
#     print(data)
#     data[:,[0,1,2,3,5,6]] = preprocessing.scale(data[:,[0,1,2,3,5,6]])
#     data[:,:] = preprocessing.scale(data[:,:])
    print(data.dtype)

#     print(data)
#     for i in range(len(data)):
#         if data[i,-1] == 0:
#             data[i,-1] = -1
#     print(data.shape)
#     data[:,[0,1,2,3,5,6]].astype(np.float32)
#     data[:,[4]].astype(np.int32)
    print(data)
    return data[:,[0,1,2,3]], data[:,[4]]

In [105]:
# np.set_printoptions(threshold='nan')

from sklearn.preprocessing import normalize
from sklearn import preprocessing
X, y = create_data(data)
# print(X)
# print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
print(X_train.shape)
print(X_train)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

y_train=np.reshape(y_train,(-1))
y_test=np.reshape(y_test,(-1))
# y_train = y_train.astype('int')
# y_test = y_test.astype('int')

y_train = y_train.astype('float32')
y_test = y_test.astype('float32')
print(X_train.dtype,y_train.dtype)
print(y_train)

object
[[2014 21 1 ... 9 107 27077]
 [2011 21 1 ... 1 108 28285]
 [2011 21 1 ... 4 108 28285]
 ...
 [2010 54 109 ... 5 15 8668]
 [2012 54 109 ... 1 35 9429]
 [2012 54 109 ... 14 35 9429]]
(18046, 4)
[[2014 51 59 57]
 [2011 42 21 34]
 [2016 21 29 48]
 ...
 [2016 21 49 33]
 [2016 39 67 34]
 [2013 51 77 44]]
float32 float32
[6. 2. 6. ... 2. 1. 5.]


In [85]:
from sklearn.svm import SVC
clf = SVC()
# y_train.describe() 
# X_train=data['0','3','4',]
clf.fit(X_train, y_train)
clf.score(X_test, y_test)
y=clf.predict(X_test)

/Users/Macbook/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.25199468085106386

In [98]:

print(y.mean())
print(y_test.mean())
print(abs(y-y_test))
from keras.optimizers import SGD,adam
from keras.models import Sequential
from keras.layers.core import Dense, Activation
model = Sequential()  #层次模型
model.add(Dense(20,input_dim=4,init='uniform')) #输入层，Dense表示BP层
model.add(Activation('relu'))  #添加激活函数
model.add(Dense(20)) #输入层，Dense表示BP层
model.add(Activation('relu'))  #添加激活函数
model.add(Dense(20)) #输入层，Dense表示BP层
model.add(Activation('relu'))  #添加激活函数
model.add(Dense(1))  #输出层
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy']) #编译模型
model.fit(X_train, y_train, nb_epoch = 1000, batch_size = 100) #训练模型1000次


-7.44765192082815e-16
0.005605349
[[0.05486765891468989 3.57472432210848e-09 0.02057537824070918 ...
  0.09601840361797345 0.19889526426636708 0.05486765891468989]
 [4.945326093075408e-10 0.054867662983946824 0.03429228116851332 ...
  0.15088606302719595 0.2537629236755896 4.945326093075408e-10]
 [0.020575371783925822 0.03429229070548839 0.01371690889005489 ...
  0.13031069074873752 0.23318755139713115 0.020575371783925822]
 ...
 [0.027433829210078642 0.027433833279335573 0.006858451463902071 ...
  0.1234522333225847 0.22632909397097833 0.027433829210078642]
 [4.945326093075408e-10 0.054867662983946824 0.03429228116851332 ...
  0.15088606302719595 0.2537629236755896 4.945326093075408e-10]
 [0.08915994604545395 0.034292283556039735 0.05486766537147324 ...
  0.061726116487209395 0.164602977135603 0.08915994604545395]]


/Users/Macbook/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(20, input_dim=4, kernel_initializer="uniform")`
  if __name__ == '__main__':
/Users/Macbook/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:17: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/1000
18046/18046 [==============================] - 1s 39us/step - loss: -0.0337 - acc: 0.0000e+00
Epoch 2/1000
18046/18046 [==============================] - 0s 17us/step - loss: -0.0301 - acc: 0.0000e+00
Epoch 3/1000
18046/18046 [==============================] - 0s 14us/step - loss: -0.0301 - acc: 0.0000e+00
Epoch 4/1000
18046/18046 [==============================] - 0s 13us/step - loss: -0.0301 - acc: 0.0000e+00
Epoch 5/1000
18046/18046 [==============================] - 0s 13us/step - loss: -0.0301 - acc: 0.0000e+00
Epoch 6/1000
18046/18046 [==============================] - 0s 13us/step - loss: -0.0301 - acc: 0.0000e+00
Epoch 7/1000
18046/18046 [==============================] - 0s 17us/step - loss: -0.0301 - acc: 0.0000e+00
Epoch 8/1000
18046/18046 [==============================] - 0s 14us/step - loss: -0.0301 - acc: 0.0000e+00
Epoch 9/1000
18046/18046 [==============================] - 0s 13us/step - loss: -0.0301 - acc: 0.0000e+00
Epoch 10/1000
18046/18046 [==========

In [8]:
from sklearn.linear_model import LinearRegression
import numpy as np
# 创建并拟合模型
model = LinearRegression()

# model.fit(X,_train, y_train)
# y=model.predict(X_test)


ValueError: only 2 non-keyword arguments accepted

In [107]:
for _ in range(len(y)):
    print(y[_],"  ",y_test[_])
print(y.mean())
print(y_test.mean())

28.927856    2.0
17.454102    1.0
25.433533    8.0
28.995422    1.0
23.192871    3.0
23.934143    6.0
30.140808    1.0
24.177917    1.0
23.089722    107.0
24.650757    8.0
26.61029    87.0
25.28717    3.0
28.824402    12.0
31.716614    4.0
29.631897    8.0
27.92041    17.0
32.82483    16.0
27.326843    1.0
26.50653    8.0
30.015991    10.0
25.416443    4.0
25.144043    18.0
27.762207    30.0
25.474182    17.0
25.64087    1.0
24.625854    1.0
28.27124    1.0
21.555603    2.0
29.776611    9.0
24.45874    2.0
28.300842    1.0
17.197205    8.0
25.27887    64.0
31.114197    1.0
35.405945    1.0
23.251343    24.0
35.222107    4.0
20.141663    3.0
24.36267    2.0
32.050354    2.0
29.60321    1.0
23.746338    8.0
25.087402    1.0
24.241516    23.0
21.475403    1.0
32.61023    13.0
32.76825    1.0
19.120361    1.0
24.22461    6.0
21.745972    45.0
22.57611    1.0
20.820618    3.0
20.120605    1.0
24.578186    18.0
23.515808    17.0
22.91626    48.0
25.070007    4.0
25.468079    5.0
27.96344    